"""
src/rag/rag_chain.py
=====================
LangChain RAG pipeline: retrieve relevant standard chunks → Gemini generates audit note.

The RAG chain works in 2 steps:
  1. RETRIEVE: FAISS finds the top-k most relevant GRI/TCFD/SASB/ISSB chunks
               for the flagged claim
  2. GENERATE: Gemini 1.5 Flash synthesises a structured audit observation
               based ONLY on the retrieved chunks (not open-ended hallucination)

Hallucination mitigation:
  - Gemini only sees retrieved standard text — no open-ended web search
  - System prompt instructs it to cite the specific standard reference
  - Retrieval scores are logged — low-confidence retrievals are flagged

Usage:
    chain = RagChain.build(vector_store, gemini_api_key="...")
    obs = chain.generate_audit_observation(
        claim="We reduced Scope 1 emissions by 40%.",
        shap_narrative="Missing baseline year.",
        question="What GRI disclosure is required here?"
    )
    print(obs.structured_note)
    print(obs.standards_cited)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from langchain.prompts import ChatPromptTemplate
from langchain.schema.output_parser import StrOutputParser
from langchain.schema.runnable import RunnablePassthrough
from langchain_google_genai import ChatGoogleGenerativeAI
from loguru import logger

from config.settings import app_cfg, gemini_cfg
from src.rag.vector_store import SearchResult, VectorStore


# ── Output dataclass ──────────────────────────────────────────────────────────

@dataclass
class AuditObservation:
    """Structured audit observation generated by Gemini."""
    claim_text: str
    structured_note: str                    # full Gemini output
    standards_cited: list[str] = field(default_factory=list)   # e.g. ["GRI 305-1", "TCFD"]
    retrieved_chunks: list[SearchResult] = field(default_factory=list)
    retrieval_confidence: float = 0.0       # average score of top-k chunks
    low_confidence_flag: bool = False       # True if retrieval was poor
    shap_narrative: str = ""

    def to_dict(self) -> dict:
        return {
            "claim_text": self.claim_text,
            "structured_note": self.structured_note,
            "standards_cited": self.standards_cited,
            "retrieval_confidence": round(self.retrieval_confidence, 4),
            "low_confidence_flag": self.low_confidence_flag,
            "shap_narrative": self.shap_narrative,
        }


# ── Prompt template ───────────────────────────────────────────────────────────
# Designed for structured, auditor-facing output
# Instructions force Gemini to stay within retrieved context

AUDIT_OBSERVATION_TEMPLATE = """You are a senior ESG auditor at a Big 4 firm.
You are reviewing a sustainability claim extracted from a company's ESG report.

RELEVANT REGULATORY STANDARDS (retrieved from GRI/TCFD/SASB/ISSB knowledge base):
{context}

ESG CLAIM UNDER REVIEW:
"{claim}"

EXPLAINABILITY NOTE (from FinBERT SHAP analysis):
{shap_narrative}

{auditor_question}

Generate a structured audit observation in exactly this format:

**Standard Reference:** [cite the most relevant standard from the context above]

**Compliance Assessment:** [COMPLIANT / PARTIALLY COMPLIANT / NON-COMPLIANT / INSUFFICIENT EVIDENCE]

**Evidence Gaps Identified:**
- [List specific missing disclosures or data points required by the cited standard]
- [Each gap on its own line]

**Risk Level:** [LOW / MEDIUM / HIGH / CRITICAL]

**Recommended Auditor Action:**
[Concrete next step — e.g. "Request the company's CDP submission for comparison" or "Verify the 2019 baseline figure against the prior-year 10-K"]

**Grounding Note:** Only use information from the regulatory standards provided above. Do not introduce external knowledge.
"""

AUDITOR_QUESTION_PREFIX = "AUDITOR QUESTION: "


# ── Main class ────────────────────────────────────────────────────────────────

class RagChain:
    """
    Retrieval-Augmented Generation pipeline for ESG audit observations.

    Combines:
    - VectorStore (FAISS) for standard retrieval
    - Gemini 1.5 Flash for structured observation generation
    - LangChain for orchestration

    Low retrieval confidence threshold: if the top chunk score < 0.4,
    a warning flag is set on the observation (retrieval was uncertain).
    """

    LOW_CONFIDENCE_THRESHOLD = 0.4

    def __init__(
        self,
        vector_store: VectorStore,
        llm: ChatGoogleGenerativeAI,
    ) -> None:
        self.vector_store = vector_store
        self.llm = llm
        self._prompt = ChatPromptTemplate.from_template(AUDIT_OBSERVATION_TEMPLATE)
        self._output_parser = StrOutputParser()
        logger.info("RagChain initialised")

    @classmethod
    def build(
        cls,
        vector_store: VectorStore,
        api_key: str = gemini_cfg.api_key,
        model_name: str = gemini_cfg.model_name,
    ) -> "RagChain":
        """
        Factory method — build a RagChain with a configured Gemini LLM.

        Args:
            vector_store: Pre-built/loaded VectorStore
            api_key:      Google AI Studio API key
            model_name:   Gemini model ID (default: gemini-1.5-flash)
        """
        models_to_try = ["gemini-3.1-flash-lite", "gemini-2.5-flash", "gemini-2.0-flash", "gemini-3.5-flash", "gemini-flash-latest"]
        ordered_models = []
        for m in [model_name] + models_to_try:
            if m and m not in ordered_models:
                ordered_models.append(m)

        llm_instances = []
        for model in ordered_models:
            llm_instances.append(ChatGoogleGenerativeAI(
                model=model,
                google_api_key=api_key,
                temperature=0.1,    # low temperature for consistent, factual audit notes
                max_output_tokens=8192,
            ))

        primary_llm = llm_instances[0]
        if len(llm_instances) > 1:
            llm = primary_llm.with_fallbacks(llm_instances[1:])
        else:
            llm = primary_llm

        logger.info(f"Gemini LLM configured with model: {ordered_models[0]} (fallbacks: {ordered_models[1:]})")
        return cls(vector_store=vector_store, llm=llm)

    # ── Public API ────────────────────────────────────────────────────────────

    def generate_audit_observation(
        self,
        claim: str,
        shap_narrative: str = "",
        question: Optional[str] = None,
        top_k: int = app_cfg.rag_top_k,
        standard_filter: Optional[str] = None,
    ) -> AuditObservation:
        """
        Generate a structured audit observation for a flagged claim.

        Args:
            claim:           The ESG claim text to audit
            shap_narrative:  Human-readable SHAP explanation (from ShapExplainer)
            question:        Optional auditor question to answer
            top_k:           Number of standard chunks to retrieve
            standard_filter: Restrict retrieval to one standard ("GRI", "TCFD", etc.)

        Returns:
            AuditObservation with structured note, standards cited, retrieval confidence
        """
        logger.info(f"Generating audit observation for: '{claim[:60]}...'")

        # 1. RETRIEVE relevant standard chunks
        search_results = self.vector_store.search(
            query=claim,
            top_k=top_k,
            standard_filter=standard_filter,
        )

        if not search_results:
            logger.warning("No standard chunks retrieved — knowledge base may be empty")
            return AuditObservation(
                claim_text=claim,
                structured_note=(
                    "⚠️ Unable to generate audit observation: "
                    "knowledge base is empty. Please run vector_store.build_from_directory() "
                    "with GRI/TCFD/SASB/ISSB PDFs."
                ),
                shap_narrative=shap_narrative,
            )

        # 2. FORMAT context for the prompt
        context = self._format_context(search_results)
        avg_score = sum(r.score for r in search_results) / len(search_results)
        low_confidence = avg_score < self.LOW_CONFIDENCE_THRESHOLD

        if low_confidence:
            logger.warning(
                f"Low retrieval confidence (avg={avg_score:.3f}) — "
                "standard chunks may not be closely relevant"
            )

        # 3. BUILD prompt
        auditor_q = ""
        if question:
            auditor_q = f"{AUDITOR_QUESTION_PREFIX}{question}"

        prompt_input = {
            "context": context,
            "claim": claim,
            "shap_narrative": shap_narrative or "No SHAP explanation available.",
            "auditor_question": auditor_q,
        }

        # 4. GENERATE with Gemini
        try:
            chain = self._prompt | self.llm | self._output_parser
            structured_note = chain.invoke(prompt_input)
            logger.success("Audit observation generated")
        except Exception as exc:
            logger.error(f"Gemini generation failed: {exc}")
            structured_note = f"Generation failed: {exc}"

        # 5. EXTRACT cited standards from output
        standards_cited = self._extract_standards(structured_note, search_results)

        return AuditObservation(
            claim_text=claim,
            structured_note=structured_note,
            standards_cited=standards_cited,
            retrieved_chunks=search_results,
            retrieval_confidence=round(avg_score, 4),
            low_confidence_flag=low_confidence,
            shap_narrative=shap_narrative,
        )

    def answer_question(
        self,
        question: str,
        top_k: int = app_cfg.rag_top_k,
    ) -> str:
        """
        Answer a free-form auditor question grounded in the standards knowledge base.
        Used by the Streamlit RAG chatbot.

        Args:
            question: Natural language question about ESG standards

        Returns:
            Answer string grounded in retrieved standard chunks
        """
        results = self.vector_store.search(question, top_k=top_k)
        if not results:
            return "Knowledge base is empty. Please build the FAISS index first."

        context = self._format_context(results)
        chatbot_prompt = ChatPromptTemplate.from_template(
            """You are an expert in ESG regulatory standards (GRI, TCFD, SASB, ISSB, EU CSRD).

Answer the following question using ONLY the provided standard excerpts.
If the answer is not in the excerpts, say so explicitly.

REGULATORY STANDARD EXCERPTS:
{context}

QUESTION: {question}

Answer:"""
        )
        chain = chatbot_prompt | self.llm | self._output_parser
        try:
            return chain.invoke({"context": context, "question": question})
        except Exception as exc:
            logger.error(f"Chatbot generation failed: {exc}")
            return f"Error generating answer: {exc}"

    # ── Private helpers ───────────────────────────────────────────────────────

    @staticmethod
    def _format_context(results: list[SearchResult]) -> str:
        """Format retrieved chunks into a numbered context block for the prompt."""
        lines = []
        for r in results:
            lines.append(
                f"[{r.rank}] {r.chunk.standard} — {r.chunk.section} "
                f"(source: {r.chunk.source_doc}, page {r.chunk.page_number}, "
                f"relevance: {r.score:.3f})\n{r.chunk.text}"
            )
        return "\n\n---\n\n".join(lines)

    @staticmethod
    def _extract_standards(note: str, results: list[SearchResult]) -> list[str]:
        """Extract cited standard names from the generated note."""
        standards = set()
        for standard in ["GRI", "TCFD", "SASB", "ISSB", "CSRD", "IFRS"]:
            if standard in note.upper():
                standards.add(standard)
        # Also add standards from retrieved chunks
        for r in results:
            if r.chunk.standard and r.chunk.standard != "UNKNOWN":
                standards.add(r.chunk.standard)
        return sorted(standards)
